version: '3.8'

services:
  web:
    build: ./
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/web/static
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=psql_user
      - POSTGRES_PASSWORD=psql_user
      - POSTGRES_DB=psql_db

volumes:
  postgres_data:
  static_volume:
